### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by aneeqahmed522** [somanath-goudar/html-css-projects#2]
Can you help with finding images in these projects of cloning. I'm new to this field. I want to copy this and implement it on my vs code and understand the code. If you've provided the images let me where, Thank You!

**Comment by somanath-goudar** [comment]
Hi, The images I used are directly from the internet. Just copy paste the URL in the src of the img tag

**Comment by aneeqahmed522** [comment]
Thank you so much ! ❣️
